### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by solloron1** [alttch/shd#2]
Ubuntu 18.04 LTS on WSL

Error received after installing with pip:

`File "/usr/local/bin/shd", line 97
    print(': {} '.format(colored(devpath, color='cyan')), end='')
                                                             ^
SyntaxError: invalid syntax`

**Comment by divi255** [comment]
this happens if you're trying to run tool with Python 2. uninstall it and install with pip3 (or python3 -m pip) again

**Comment by solloron1** [comment]
Thanks!
